# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateField(auto_now_add=True, default="2017-05-13"),
            preserve_default=False,
        ),
    ]
