# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_payments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='date',
        ),
        migrations.AddField(
            model_name='consumption',
            name='date',
            field=models.DateField(auto_now_add=True, default='2017-05-13'),
            preserve_default=False,
        ),
    ]
