# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_auto_20170513_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.PositiveIntegerField()),
                ('paid', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='consumption',
            name='paid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
